repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.6.4"
    hooks:
      - id: isort
        types: [python]

  - repo: https://github.com/python/black
    rev: "20.8b1"
    hooks:
      - id: black
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.790"
    hooks:
      - id: mypy
        types: [python]
