[tool.poetry]
name = "seevr-player"
version = "0.0.0"
description = ""
authors = ["Gary Tyler <mail@garytyler.com>"]

[tool.poetry.dependencies]
python = "^3.7"
PyQt5-sip = "*"
pyqt5 = "*"
ffmpeg-python = "*"
python-vlc = "*"
qtawesome = "*"
macholib = "*"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
pyinstaller = "^3.6"
flake8 = "*"
isort = "*"
mypy = "*"
pre-commit = "*"
pytest = "*"
pytest-qt = "*"
pywin32-ctypes = { version = "^0.2.0", markers = "sys_platform == 'win32'" }
typer = "*"
colorama = "*"
shellingham = "*"
