[tool.poetry]
name = "seevr-player"
version = "0.0.0"
description = ""
authors = ["Gary Tyler <mail@garytyler.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyQt5-sip = "*"
pyqt5 = "*"
ffmpeg-python = "*"
python-vlc = "*"
qtawesome = "*"


[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
pyinstaller = "*"
flake8 = "*"
isort = "*"
mypy = "*"
pre-commit = "*"
pytest = "*"
pytest-qt = "*"
pywin32-ctypes = { version = "^0.2.0", markers = "sys_platform == 'win32'" }
